import { Car, AppLanguage } from './types';

export const PHOTO_PLACEHOLDERS = [
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000&auto=format&fit=crop', // Ferrari
  'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1000&auto=format&fit=crop', // Porsche
  'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1000&auto=format&fit=crop', // Yellow Lami
  'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=1000&auto=format&fit=crop', // Audi/Aston
  'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1000&auto=format&fit=crop', // G wagon
  'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?q=80&w=1000&auto=format&fit=crop', // Luxury Rolls
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1000&auto=format&fit=crop', // Classic sports
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1000&auto=format&fit=crop'  // Vintage Porsche
];

export const CARS_DATA: Car[] = [
  {
    id: 'car_001',
    brand: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1000'
    ],
    price: 1850,
    type: 'rent',
    transmission: 'Dual-Clutch 8-Speed',
    engine: '4.0L Twin-Turbo V8 Hybrid',
    power: 986,
    acceleration: '2.5s',
    topSpeed: 340,
    location: 'Beverly Hills, CA',
    distance: 1.4,
    rating: 4.9,
    description: 'The Ferrari SF90 Stradale redefines the hypercar segment with plug-in hybrid architecture. Experience absolute raw power paired with Formula 1 grade torque vectoring and whisper-silent urban cruising capabilities.',
    features: ['E-Drive Mode', 'Assured Premium Cover', 'Carbon Ceramic Brakes', 'LaFerrari DNA', 'Apple CarPlay'],
    dealerId: 'dealer_maranello',
    dealerName: 'Apex Cavallino Scuderia',
    dealerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'premium',
    reviews: [
      {
        id: 'rev_1',
        carId: 'car_001',
        userName: 'Julian Vance',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100',
        rating: 5,
        comment: 'Absolutely spectacular. Swipes do not do this exhaust note justice. Clean, pristine handover by the dealer.',
        date: '2026-05-18'
      },
      {
        id: 'rev_2',
        carId: 'car_001',
        userName: 'Elena Rostova',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100',
        rating: 4.8,
        comment: 'Pure adrenaline. Highly recommend opting for the premium full insurance. Made the drive stress-free.',
        date: '2026-06-01'
      }
    ]
  },
  {
    id: 'car_002',
    brand: 'Porsche',
    model: '911 GT3 RS (992)',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1000',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1000'
    ],
    price: 1400,
    type: 'rent',
    transmission: 'PDK 7-Speed',
    engine: '4.0L Naturally Aspirated Boxer-6',
    power: 518,
    acceleration: '3.0s',
    topSpeed: 296,
    location: 'Miami Beach, FL',
    distance: 3.8,
    rating: 4.95,
    description: 'An uncompromised track-day weapon optimized for public roads. Massive active aerodynamics and double-wishbone front suspension create an unparalleled connection between driver and tarmac.',
    features: ['Active Aero DRS', 'Full Roll Cage', 'Weissach Lightweight pack', 'Nürburgring Tuned', 'Track Precision App'],
    dealerId: 'dealer_stuttgart',
    dealerName: 'Stuttgart Classics & Exotics',
    dealerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'premium',
    reviews: [
      {
        id: 'rev_3',
        carId: 'car_002',
        userName: 'Garrison Cole',
        userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=100',
        rating: 5,
        comment: 'This is not a car, it is a scalpel. Cornering limits are mind-bending. Will definitely swipe right again.',
        date: '2026-06-04'
      }
    ]
  },
  {
    id: 'car_003',
    brand: 'Lamborghini',
    model: 'Revuelto V12',
    year: 2025,
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1000',
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=1000'
    ],
    price: 380000,
    type: 'buy',
    transmission: 'Dual-Clutch 8-Speed',
    engine: '6.5L V12 Hybrid',
    power: 1001,
    acceleration: '2.5s',
    topSpeed: 350,
    location: 'New York, NY',
    distance: 0.8,
    rating: 5.0,
    mileage: 1850,
    description: 'The first super sports V12 hybrid plug-in HPEV (High Performance Electrified Vehicle). A historic design ethos elevated with futuristic electric-assisted launch control.',
    features: ['Carbon Monocell', '1001 Horsepower', 'Custom Ad Personam Premium Paint', 'Full Titanium Exhaust', 'Zero Emissions Mode'],
    dealerId: 'dealer_santagata',
    dealerName: 'Empire Bulls Dealer',
    dealerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'basic',
    reviews: []
  },
  {
    id: 'car_004',
    brand: 'Mercedes-Benz',
    model: 'G63 AMG Brabus',
    year: 2023,
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1000',
      'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?q=80&w=1000'
    ],
    price: 950,
    type: 'rent',
    transmission: 'Speedshift 9-Speed',
    engine: '4.0L Biturbo V8 Brabus 800',
    power: 800,
    acceleration: '4.1s',
    topSpeed: 240,
    location: 'Malibu, CA',
    distance: 5.2,
    rating: 4.85,
    description: 'Take command of the road with the commanding presence of the G63 AMG. Upgraded by Brabus, this unit offers custom leather piping, a starry night starlight ceiling, and deep, resonant dual side-pipe valved sports exhausts.',
    features: ['Starlight Roof Headliner', 'Brabus Widebody Kit', 'Burmester High-End Sound', 'Bulletproof Grade Glass', 'Dual Active Diff-Locks'],
    dealerId: 'dealer_brabus',
    dealerName: 'Malibu Concierge Line',
    dealerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'basic',
    reviews: [
      {
        id: 'rev_4',
        carId: 'car_004',
        userName: 'Marco Rossi',
        userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100',
        rating: 4.7,
        comment: 'Amazing presence on the highway. Loud, aggressive, but surprisingly luxurious inside.',
        date: '2026-05-12'
      }
    ]
  },
  {
    id: 'car_005',
    brand: 'Rolls-Royce',
    model: 'Spectre Electric',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1632245889029-e406faaa34cd?q=80&w=1000',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1000'
    ],
    price: 450000,
    type: 'buy',
    transmission: 'Single-Speed Seamless',
    engine: 'Dual Synchronous Electric Motor',
    power: 577,
    acceleration: '4.4s',
    topSpeed: 250,
    location: 'West Palm Beach, FL',
    distance: 2.1,
    rating: 4.98,
    mileage: 75,
    description: 'The world’s ultra-luxury electric super coupe. Operating in sublime silence, the Spectre delivers instant magic-carpet ride suspension and an bespoke planetary starry cabin lining.',
    features: ['Starlight Bespoke Doors', 'Magic Carpet Air Suspension', 'Polished Monolith Grill', 'Organ-stop air vents', 'Self-Closing Doors'],
    dealerId: 'dealer_goodwood',
    dealerName: 'Goodwood Heritage Guild',
    dealerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'premium',
    reviews: [
      {
        id: 'rev_5',
        carId: 'car_005',
        userName: 'Sienna Sterling',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=100',
        rating: 5,
        comment: 'Sublime silence. There is literally nothing that compares to an electric Rolls. High luxury represented well.',
        date: '2026-06-11'
      }
    ]
  },
  {
    id: 'car_006',
    brand: 'Aston Martin',
    model: 'DBS 770 Ultimate',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=1000',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000'
    ],
    price: 360000,
    type: 'buy',
    transmission: 'ZF 8-Speed Automatic',
    engine: '5.2L Twin-Turbo V12',
    power: 759,
    acceleration: '3.2s',
    topSpeed: 340,
    location: 'London, UK',
    distance: 12.0,
    rating: 4.92,
    mileage: 450,
    description: 'A ferocious farewell to Aston Martin’s front-engined V12 masterpiece. Limitless torque meets structural stiffening and carbon fiber aerodynamic styling to create an absolute modern legend.',
    features: ['Pure Carbon Aero Trim', 'Signature V12 Growl', 'Enclosed bespoke watch compartment', 'Limited 1 of 300 badge', 'Alcantara Monolith seating'],
    dealerId: 'dealer_gaydon',
    dealerName: 'Gaydon Elite Club',
    dealerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'none',
    reviews: []
  },
  {
    id: 'car_007',
    brand: 'Mazda',
    model: 'MX-5 Miata Roadster',
    year: 2023,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1000'
    ],
    price: 65,
    type: 'rent',
    transmission: '6-Speed Manual',
    engine: '2.0L SkyActiv-G 4-Cylinder',
    power: 181,
    acceleration: '5.7s',
    topSpeed: 220,
    location: 'Santa Monica, CA',
    distance: 2.5,
    rating: 4.90,
    description: 'The standard of lightweight sports roadsters. Delivering pure, unadulterated open-air driving pleasure with a crisp manual transmission.',
    features: ['Brembo Front Brakes', 'Recaro Sports Seats', 'Soft-Top Convertible', 'Limited Slip Differential'],
    dealerId: 'user_miata_fan',
    dealerName: 'Sam Wheeler',
    dealerAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100',
    insuranceLevel: 'basic',
    reviews: []
  },
  {
    id: 'car_008',
    brand: 'Toyota',
    model: 'GR Supra 3.0',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1000'
    ],
    price: 135,
    type: 'rent',
    transmission: '8-Speed Sport Automatic',
    engine: '3.0L Turbocharged Inline-6',
    power: 382,
    acceleration: '3.9s',
    topSpeed: 250,
    location: 'Glendale, CA',
    distance: 4.1,
    rating: 4.88,
    description: 'A legendary Japanese tuner badge returned with a roaring double-scroll turbocharged heart. Compact styling with spectacular drifts.',
    features: ['Active Sport Exhaust', 'Launch Control', 'JBL Premium Sound', 'Adaptive Variable Suspension'],
    dealerId: 'dealer_toyota_sport',
    dealerName: 'Westside imports Co.',
    dealerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=120',
    insuranceLevel: 'basic',
    reviews: []
  },
  {
    id: 'car_009',
    brand: 'Honda',
    model: 'Civic Type R (FL5)',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=1000'
    ],
    price: 115,
    type: 'rent',
    transmission: '6-Speed Manual + Rev Match',
    engine: '2.0L VTEC Turbocharged 4-Cylinder',
    power: 315,
    acceleration: '5.3s',
    topSpeed: 275,
    location: 'Pasadena, CA',
    distance: 7.2,
    rating: 4.94,
    description: 'Sublime mechanical precision in a hot hatch. Track-tuned dual-axis front strut suspension completely eliminates torque steer.',
    features: ['Triple Center Exhaust', 'LogR telemetry system', 'Alcantara Sports Wheel', 'Brembo calipers'],
    dealerId: 'user_ctr_jason',
    dealerName: 'Jason Park',
    dealerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100',
    insuranceLevel: 'basic',
    reviews: []
  },
  {
    id: 'car_010',
    brand: 'Tesla',
    model: 'Model 3 Performance',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=1000'
    ],
    price: 90,
    type: 'rent',
    transmission: 'Dual-Motor Dual Drive',
    engine: 'Dual AC Electric Motors (AWD)',
    power: 510,
    acceleration: '2.9s',
    topSpeed: 262,
    location: 'Culver City, CA',
    distance: 3.0,
    rating: 4.82,
    description: 'Mind-boggling electric launch in a practical sport sedan. Featuring the brand new Track Mode V3 and active damper chassis tuning.',
    features: ['Track Mode V3', 'Tesla Autopilot Lite', 'Satin Black Aero Wheels', 'Carbon Fiber Lip Spoiler'],
    dealerId: 'dealer_ev_network',
    dealerName: 'Apex Electrics',
    dealerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=120',
    insuranceLevel: 'premium',
    category: 'car',
    drivetrain: 'AWD',
    displacement: 'Electric',
    reviews: []
  },
  {
    id: 'bike_001',
    brand: 'Ducati',
    model: 'Panigale V4 R',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1000'
    ],
    price: 240,
    type: 'rent',
    transmission: '6-Speed Manual',
    engine: '1103cc Desmosedici Stradale V4',
    power: 240,
    acceleration: '2.7s',
    topSpeed: 315,
    location: 'Malibu, CA',
    distance: 4.5,
    rating: 4.95,
    description: 'The pinnacle of track engineering. With lightened carbon bodywork, titanium conrods, and dry clutch, this racing machine offers the ultimate two-wheel adrenaline rush.',
    features: ['Akrapovič Racing Exhaust', 'Ohlins Electronic Damper', 'Brembo Stylema R Brakes', 'Lean-Angle Traction Control'],
    dealerId: 'dealer_maranello',
    dealerName: 'Apex Cavallino Scuderia',
    dealerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=120&auto=format&fit=crop',
    insuranceLevel: 'premium',
    category: 'motorcycle',
    drivetrain: 'RWD',
    displacement: '1.1L',
    reviews: []
  },
  {
    id: 'bike_002',
    brand: 'BMW',
    model: 'M 1000 RR',
    year: 2024,
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1000'
    ],
    price: 220,
    type: 'rent',
    transmission: '6-Speed Manual with Quickshifter',
    engine: '999cc Water-cooled Inline-4',
    power: 212,
    acceleration: '2.8s',
    topSpeed: 306,
    location: 'Beverly Hills, CA',
    distance: 2.1,
    rating: 4.9,
    description: 'The first pure BMW M motorcycle. Featuring full carbon-fiber M winglets generating massive high-speed downforce, carbon-fiber wheels, and M brakes.',
    features: ['M Carbon Winglets', 'Titanium Exhaust System', 'M Laptrigger GPS', 'Pro Riding Modes'],
    dealerId: 'dealer_stuttgart',
    dealerName: 'Stuttgart Classics & Exotics',
    dealerAvatar: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=120',
    insuranceLevel: 'premium',
    category: 'motorcycle',
    drivetrain: 'RWD',
    displacement: '1.0L',
    reviews: []
  }
];

export const DICTIONARY: Record<AppLanguage, any> = {
  [AppLanguage.EN]: {
    appName: 'Veloce',
    tagline: 'LUXURY CARS MADE SIMPLE',
    swipeToRent: 'Swipe Right to Like, Left to Pass',
    nearbyRentals: 'Nearby Rentals',
    luxuryLevel: 'Category',
    buy: 'Buy',
    rent: 'Rent',
    perDay: '/ day',
    insuranceIncluded: 'Full Insurance Included',
    basicInsurance: 'Basic Insurance',
    premiumInsurance: 'Premium Full Insurance',
    noInsurance: 'No Extra Insurance',
    likedCars: 'Liked Cars',
    inbox: 'Messages',
    dashboard: 'Profile & Settings',
    roleDealer: 'Dealer',
    roleUser: 'User',
    startReservation: 'Book This Car',
    totalPrice: 'Total Price',
    selectDates: 'Select Dates',
    duration: 'Duration',
    location: 'Pickup Location',
    specs: 'Specifications',
    acceleration: '0 - 100 km/h',
    power: 'Horsepower',
    topSpeed: 'Maximum Velocity',
    engine: 'Engine Type',
    transmission: 'Transmission',
    distance: 'Distance From You',
    dealerLabel: 'Seller / Dealer',
    notifications: 'Notifications',
    paymentSecure: 'Secure Payment',
    paymentSuccess: 'Payment Successful',
    payWithCard: 'Pay with Credit Card',
    searchPlaceholder: 'Search brands (Ferrari, Porsche, AMG)...',
    dealerPanel: 'Dealer Panel',
    regularClientPanel: 'User Panel',
    createTinderProfile: 'List a Car',
    draftListingIntro: 'Add your car here to show it in the swipe feed so other users can book or purchase it.',
    brandName: 'Car Brand',
    carModel: 'Car Model',
    priceVal: 'Price per day',
    addPhotos: 'Upload Photos',
    uploadSuccess: 'Photo added successfully',
    publishListing: 'Add Vehicle to Swiper Feed',
    offlineNotice: 'Offline Mode',
    syncedLabel: 'Cloud Connected & Private',
    reviewsCount: 'Verified Reviews',
    logout: 'Sign Out of Profile',
    loginPrompt: 'Sign In to Your Account',
    appleLogin: 'Sign in with Apple',
    googleLogin: 'Sign in with Google'
  },
  [AppLanguage.ES]: {
    appName: 'Veloce',
    tagline: 'COCHES DE LUJO AL ALCANCE',
    swipeToRent: 'Desliza a la derecha para me gusta, izquierda para pasar',
    nearbyRentals: 'Alquileres Cercanos',
    luxuryLevel: 'Categoría',
    buy: 'Comprar',
    rent: 'Alquilar',
    perDay: '/ día',
    insuranceIncluded: 'Seguro Completo Incluido',
    basicInsurance: 'Seguro Básico',
    premiumInsurance: 'Seguro a Todo Riesgo',
    noInsurance: 'Sin Seguro Adicional',
    likedCars: 'Mis Favoritos',
    inbox: 'Mensajes',
    dashboard: 'Mi Perfil',
    roleDealer: 'Concesionario',
    roleUser: 'Usuario',
    startReservation: 'Reservar Coche',
    totalPrice: 'Precio Total',
    selectDates: 'Seleccionar Fechas',
    duration: 'Duración',
    location: 'Lugar de Recogida',
    specs: 'Especificaciones',
    acceleration: '0 a 100 km/h',
    power: 'Potencia',
    topSpeed: 'Velocidad Máxima',
    engine: 'Motor',
    transmission: 'Transmisión',
    distance: 'Distancia de ti',
    dealerLabel: 'Vendedor / Concesionario',
    notifications: 'Notificaciones',
    paymentSecure: 'Pago Seguro',
    paymentSuccess: 'Pago Completado',
    payWithCard: 'Pagar con Tarjeta de Crédito',
    searchPlaceholder: 'Buscar marcas (Ferrari, Porsche, Aston)...',
    dealerPanel: 'Consola de Distribuidor',
    regularClientPanel: 'Consola del Usuario',
    createTinderProfile: 'Registrar Coche',
    draftListingIntro: 'Añade tu coche para mostrarlo en el feed de deslizamiento.',
    brandName: 'Marca',
    carModel: 'Modelo',
    priceVal: 'Precio por día',
    addPhotos: 'Añadir Fotos',
    uploadSuccess: 'Foto subida correctamente',
    publishListing: 'Añadir Vehículo al Catálogo',
    offlineNotice: 'Modo Offline',
    syncedLabel: 'Sincronizado con la Nube',
    reviewsCount: 'Reseñas Verificadas',
    logout: 'Cerrar Sesión de Perfil',
    loginPrompt: 'Iniciar Sesión',
    appleLogin: 'Iniciar sesión con Apple',
    googleLogin: 'Iniciar sesión con Google'
  },
  [AppLanguage.IT]: {
    appName: 'Veloce',
    tagline: 'AUTO DI LUSSO RESE SEMPLICI',
    swipeToRent: 'Scorri a destra per mi piace, sinistra per passare',
    nearbyRentals: 'Noleggi Vicini',
    luxuryLevel: 'Categoria',
    buy: 'Acquista',
    rent: 'Noleggia',
    perDay: '/ giorno',
    insuranceIncluded: 'Assicurazione Completa Inclusa',
    basicInsurance: 'Assicurazione Base',
    premiumInsurance: 'Assicurazione Kasko Completa',
    noInsurance: 'Senza Assicurazione Extra',
    likedCars: 'Preferiti',
    inbox: 'Messaggi',
    dashboard: 'Profilo',
    roleDealer: 'Concessionario',
    roleUser: 'Utente',
    startReservation: 'Prenota Auto',
    totalPrice: 'Prezzo Totale',
    selectDates: 'Seleziona Date',
    duration: 'Durata',
    location: 'Luogo di Ritiro',
    specs: 'Specifiche',
    acceleration: '0 - 100 km/h',
    power: 'Cavalli',
    topSpeed: 'Velocità Massima',
    engine: 'Motore',
    transmission: 'Cambio',
    distance: 'Distanza da te',
    dealerLabel: 'Venditore / Concessionario',
    notifications: 'Notifiche',
    paymentSecure: 'Pagamento Sicuro',
    paymentSuccess: 'Pagamento Completato',
    payWithCard: 'Paga con Carta di Credito',
    searchPlaceholder: 'Cerca marchi (Ferrari, Porsche, AMG)...',
    dealerPanel: 'Pannello Concessionario',
    regularClientPanel: 'Pannello Utente',
    createTinderProfile: 'Registra Auto',
    draftListingIntro: 'Aggiungi la tua auto per mostrarla nella bacheca di scorrimento.',
    brandName: 'Marca',
    carModel: 'Modello',
    priceVal: 'Prezzo al giorno',
    addPhotos: 'Aggiungi Foto',
    uploadSuccess: 'Foto caricata con successo',
    publishListing: 'Pubblica nel Catalogo per Swipe',
    offlineNotice: 'Modalità Offline',
    syncedLabel: 'Connesso e Sincronizzato in Cloud',
    reviewsCount: 'Recensioni Verificate',
    logout: 'Esci dal Profilo',
    loginPrompt: 'Accedi al tuo account',
    appleLogin: 'Accedi con Apple',
    googleLogin: 'Accedi con Google'
  }
};

export const AUTO_REPLIES = [
  "Fantastic choice! Your booking is confirmed, and the car is ready and clean. Let us know when you plan to pick it up.",
  "Hello from Veloce. This car is fully checked and ready for you. Do you need any assistance with directions to our location?",
  "Hi! All details and insurance are in order. We are looking forward to handing over the keys. Drive safe!",
  "Thanks for matching with this car! You can start the booking or final purchase setup from your profile whenever you are ready."
];
